//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StellarExplorer_WPF.DataViewer.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Crude_Entries
    {
        public System.Guid ce_id { get; set; }
        public string ce_ephemerisname { get; set; }
        public System.DateTime ce_from { get; set; }
        public System.DateTime ce_until { get; set; }
        public string ce_geometricallongitude { get; set; }
        public string ce_geomatricallatitude { get; set; }
        public string ce_system { get; set; }
        public byte[] ce_withasteroids { get; set; }
        public byte[] ce_withhyperbolicbodies { get; set; }
        public string ce_service { get; set; }
        public Nullable<int> ce_abovesea { get; set; }
        public string ce_intervals { get; set; }
        public string ce_object { get; set; }
    }
}
