//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StellarExplorer_WPF.DataViewer.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class eefd2969_68bf_4b2d_8bb8_43da8e913c49
    {
        public System.DateTime t_date { get; set; }
        public string t_ecllong { get; set; }
        public string t_ecllat { get; set; }
        public string t_dist { get; set; }
        public string t_speed { get; set; }
        public string t_house { get; set; }
        public string t_eclobl { get; set; }
        public string t_nutation { get; set; }
    }
}
